/**
 * IDL description of the SumModule
 *
 * This file is automatically parsed by the rurbuilder backends for the omniidl 
 * compiler. The names of the functions will become port identifiers. The names 
 * of the function variables are not used. For now, if the function variable 
 * ends with a number, like "void Sensor(in long input2);" there will be two
 * portnames created.
 *
 * Author: 
 * Copyright: 
 * Date: 
 * License: 
 */

// We have something that defines a namespace
module rur {

// We want to be able to give our class a name
interface SumModule {

  void In1(in long input);
  
  void In2(in long input);

  void Res(out long output);

};

};
